name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh pragnakalp.dev5@34.71.200.59 "cd /home/pragnakalp.dev5/github_action && git pull origin master"
      
    - name: Restart Django Service
      run: |
        ssh pragnakalp.dev5@34.71.200.59 'sudo systemctl restart myproject'